#include <stdio.h>
#include <string.h>

#include "cgic.h"
#include "globals.h"
#include "../shared/defines.h"

void printContact(void) {
  fprintf(cgiOut, "<div class=\"head1\">Contact Us!</div>\n");
  fprintf(cgiOut, "If you have problems with our site or general inquiries please feel free to contact us and we will be happy to hear from you!<br />\n");
  fprintf(cgiOut, "To report a bug please email the chief programmer listed below.\n");
  fprintf(cgiOut, "<hr />");

  fprintf(cgiOut, "<table>\n");
  fprintf(cgiOut, "<tbody>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Name\">General Inquiries</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Position\">Secretary</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "    <td>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\" colspan=\"2\">\n");
  fprintf(cgiOut, "      <label title=\"email address\">Email: </label><br />\n");
  fprintf(cgiOut, "    </td>");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"email\">\n");
  fprintf(cgiOut, "      <a href=\"mailto:c204g18@student.canterbury.ac.nz\">c204g18@student.canterbury.ac.nz</a>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "</tbody>\n");
  fprintf(cgiOut, "</table>\n");
  fprintf(cgiOut, "<hr />");

  fprintf(cgiOut, "<table>\n");
  fprintf(cgiOut, "<tbody>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Name\">Tim Carey-Smith</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Position\">Chief Programmer</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "    <td>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\" colspan=\"2\">\n");
  fprintf(cgiOut, "      <label title=\"email address\">Email: </label><br />\n");
  fprintf(cgiOut, "    </td>");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"email\">\n");
  fprintf(cgiOut, "      <a href=\"mailto:tsm20@student.canterbury.ac.nz\">tsm20@student.canterbury.ac.nz</a>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "</tbody>\n");
  fprintf(cgiOut, "</table>\n");
  fprintf(cgiOut, "<hr />");

  fprintf(cgiOut, "<table>\n");
  fprintf(cgiOut, "<tbody>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Name\">Jeremy King</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Position\">Manages The Woman Inside Of Him</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "    <td>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\" colspan=\"2\">\n");
  fprintf(cgiOut, "      <label title=\"email address\">Email: </label><br />\n");
  fprintf(cgiOut, "    </td>");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"email\">\n");
  fprintf(cgiOut, "      <a href=\"mailto:jbk20@student.canterbury.ac.nz\">jbk20@student.canterbury.ac.nz</a>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "</tbody>\n");
  fprintf(cgiOut, "</table>\n");
  fprintf(cgiOut, "<hr />");

  fprintf(cgiOut, "<table>\n");
  fprintf(cgiOut, "<tbody>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Name\">Eden Sinclair</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">  \n");
  fprintf(cgiOut, "      <label title=\"Position\">Database Extraordinaire</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "    <td>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\" colspan=\"2\">\n");
  fprintf(cgiOut, "      <label title=\"email address\">Email: </label><br />\n");
  fprintf(cgiOut, "    </td>");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"email\">\n");
  fprintf(cgiOut, "      <a href=\"mailto:ejs73@student.canterbury.ac.nz\">ejs73@student.canterbury.ac.nz</a>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "</tbody>\n");
  fprintf(cgiOut, "</table>\n");
  fprintf(cgiOut, "<hr />");

  fprintf(cgiOut, "<table>\n");
  fprintf(cgiOut, "<tbody>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">\n");
  fprintf(cgiOut, "      <label title=\"Name\">Daniel &quot;Don't mess with my piranha&quot; Bakker</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\">  \n");
  fprintf(cgiOut, "      <label title=\"Position\">Slightly Disgruntled</label>\n");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "    <td>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"describe\" colspan=\"2\">\n");
  fprintf(cgiOut, "      <label title=\"email address\">Email: </label><br />\n");
  fprintf(cgiOut, "    </td>");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "  <tr>\n");
  fprintf(cgiOut, "    <td class=\"email\">\n");
  fprintf(cgiOut, "      <a href=\"mailto:djb142@student.canterbury.ac.nz\">djb142@student.canterbury.ac.nz</a>");
  fprintf(cgiOut, "    </td>\n");
  fprintf(cgiOut, "  </tr>\n");
  fprintf(cgiOut, "</tbody>\n");
  fprintf(cgiOut, "</table>\n");
}
