#!/bin/sh

# $Header: /Users/tim/tmp/keep/uni_2004/to_keep/team44cvs/casestudy/Attic/mainco,v 1.2 2003/07/25 04:06:30 tsm20 Exp $

CLEANOUT="/home/cosc/student/tsm20/team44clean"
   CVSIN="/home/cosc/student/tsm20/team44cvs"
  MODULE="casestudy"

cd $CLEANOUT || exit

echo "pwd="`pwd`
rm -fr $MODULE

cvs -d $CVSIN export -f -r HEAD $MODULE

echo "----------------------------------"
echo "Start perms "$CLEANOUT

echo "Add rw for group (all files)"
echo "Add x  for group (dirs and scripts)"
chmod ug+rwX  `find $CLEANOUT`
echo "Remove perms for other"
chmod o-rwx `find $CLEANOUT`

# at this point:
#   other has no perms
#   group has rx for dirs and scripts
#         has r  for random files
