#!/bin/sh

# $Header: /Users/tim/tmp/keep/uni_2004/to_keep/team44cvs/casestudy/Attic/team44_mainco,v 1.6 2003/05/12 06:31:08 tsm20 Exp $

CLEANOUT="/home/cosc/student/tsm20/team44clean"

cd $CLEANOUT || exit

echo "pwd="`pwd`
rm -fr casestudy

cvs -d /home/cosc/student/tsm20/team44cvs/ export -f -r HEAD casestudy

echo "----------------------------------"
echo "Start perms "$CLEANOUT

echo "Add rw for group (all files)"
echo "Add x  for group (dirs and scripts)"
chmod g+rwX `find $CLEANOUT`
echo "Remove perms for other"
chmod o-rwx `find $CLEANOUT`

# at this point: 
#   other has no perms
#   group has rwx for dirs and scripts
#         has rw  for random files

echo "Add execute perm for other (casestudy)"
chmod o+x $CLEANOUT
chmod o+x $CLEANOUT/casestudy
echo "web - Add execute perm for other (all dirs and scripts under)"
chmod o+X `find $CLEANOUT/casestudy/web`
echo "web - Add read perm for other (all files under)"
chmod o+r `find $CLEANOUT/casestudy/web -type f`
echo "web - Add read perm for other (.htpasswd)"
chmod o+r $CLEANOUT/casestudy/.htpasswd

