#!/bin/sh
# $Header: /Users/tim/tmp/keep/uni_2004/to_keep/team44cvs/casestudy/Attic/team44_webperms,v 1.4 2003/05/26 05:11:22 tsm20 Exp $

chmod g+rx web
chmod -R g+r web
chmod g+x `find web -type d`
