#!/bin/sh

FILES=`find . |grep "\.[ch]$" |grep -v "CVS" |grep -v "cgic"`
REPLACES="malloc realloc calloc"

for f in $FILES; do
    for r in $REPLACES; do
	sed -e "s/$r(/$r_m(/g" $f >$f.tmp
	cat $f.tmp >$f
	rm -f $f.tmp
    done
done
